collision_zone_base_diameter: 0.1
color_scheme:
  drl: tab:blue
  dwa: tab:green
  ego: tab:grey
  mpc: tab:red
  rlca: tab:purple
  teb: tab:orange
goal_marker: '*'
goal_point_color: tab:brown
goal_size: 5
labels:
  drl: DRL
  dwa: DWA
  ego: EGO
  mpc: MPC
  rlca: RLCA
  teb: TEB
most_recent_file: data_21-11-04_13:16:31.json
path_alpha: 0.5
path_size: 0.5
plot_collision_zones: true
plot_collisions: null
plot_qualitative: true
specified_data_filename: null
specify_data: true
start_marker: ^
start_point_color: tab:grey
start_size: 5
