version: '3'
services:
  ros:
    image: train_golbalplan
    # command: tail -f /dev/null
    volumes: 
      # - .:/root/catkin_ws/src/arena-rosnav
      - /home/sun/arena-rosnav/Docker:/root/catkin_ws/src/arena-rosnav/Docker/
    environment:
      - DISPLAY=novnc:0.0
      - AGENT_NAME=DRL_LOCAL_PLANNER 
      - NUM_SIM_ENVS=1
      - CONFIG_FILE=rule_01
    # env_file:
    #   # - ./Docker/ros.env
    networks:
      - x11

  novnc:  
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no
    # env_file:
    #   - ./Docker/novnc.env
    ports:
      - "8080:8080"
    networks:
      - x11
    container_name: novnc
networks:
  x11: