#global_configs_folder: "configs/default_configs/"
#global_planner_class: "global_planners.ROSGlobalPlanner.ROSGlobalPlanner"
seed: 10452357
change_map: False
min_dist: 0
static: 0
dynamic: 20
map_type: "outdoor"
map_height: 250
map_width: 250
map_resolution: 0.11
indoor_prob: 0.5
indoor_corridor_radius: 10
indoor_iterations: 50
indoor_room_number: 3
indoor_room_width: 75
indoor_room_height: 70
indoor_room_no_overlap: True
outdoor_obstacle_number: 15
outdoor_obstacle_extra_radius: 6