1:
  dynamic_human: 8
  dynamic_robot: 2
  static: 0
2:
  dynamic_human: 5
  dynamic_robot: 7
  static: 0
3:
  dynamic_human: 5
  dynamic_robot: 2
  static: 0
4:
  dynamic_human: 5
  dynamic_robot: 2
  static: 0
5:
  dynamic_human: 5
  dynamic_robot: 2
  static: 0
6:
  dynamic_human: 5
  dynamic_robot: 2
  static: 0
7:
  dynamic_human: 5
  dynamic_robot: 2
  static: 0
