# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

1:
  static: 0
  dynamic_human: 6
  dynamic_robot: 2
2:
  static: 0
  dynamic_human: 8
  dynamic_robot: 1
3:
  static: 0
  dynamic_human: 8
  dynamic_robot: 1
4:
  static: 0
  dynamic_human: 8
  dynamic_robot: 1
5:
  static: 0
  dynamic_human: 8
  dynamic_robot: 1
6:
  static: 0
  dynamic_human: 8
  dynamic_robot: 1
7:
  static: 0
  dynamic_human: 8
  dynamic_robot: 1
