# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

1:
  static: 0
  dynamic: 0
2:
  static: 2
  dynamic: 0
3:
  static: 4
  dynamic: 0
4:
  static: 2
  dynamic: 2
5:
  static: 2
  dynamic: 3
6:
  static: 3
  dynamic: 5
7:
  static: 3
  dynamic: 7
