1:
  dynamic_human: 0
  dynamic_robot: 0
  static: 0
2:
  dynamic_human: 3
  dynamic_robot: 0
  static: 0
3:
  dynamic_human: 4
  dynamic_robot: 1
  static: 0
4:
  dynamic_human: 5
  dynamic_robot: 2
  static: 0
5:
  dynamic_human: 6
  dynamic_robot: 3
  static: 0
6:
  dynamic_human: 6
  dynamic_robot: 3
  static: 0
7:
  dynamic_human: 7
  dynamic_robot: 3
  static: 0
8:
  dynamic_human: 8
  dynamic_robot: 4
  static: 0
9:
  dynamic_human: 9
  dynamic_robot: 4
  static: 0
10:
  dynamic_human: 10
  dynamic_robot: 4
  static: 0
